version: '3.8'
services:
  web:
    image: maxisme/crypter:latest
    deploy:
      mode: global
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.maxmeuk.rule=Host(`crypter.co.uk`)"
        - "traefik.http.services.maxmeuk.loadbalancer.server.port=8080"
        - "traefik.http.routers.maxmeuk.middlewares=404"
    networks:
      - traefik

networks:
  traefik:
    external: true