version: '3.8'
services:
  web:
    image: maxisme/crypter.co.uk:latest
    deploy:
      mode: global
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.cryptercouk.rule=Host(`crypter.co.uk`)"
        - "traefik.http.services.cryptercouk.loadbalancer.server.port=8080"
        - "traefik.http.routers.cryptercouk.middlewares=404"
    networks:
      - traefik

networks:
  traefik:
    external: true